### ISSUE TITLE
Add the actual script or please archive the project

### ISSUE THREAD

**Issue by NGenetzky** [bojanpotocnik/segger-rtt-viewer#1]

**Comment by bojanpotocnik** [comment]
Sorry for the late response.
It turned out as I somehow lost (deleted?) the original local repository as it was made as "quick hack" and then there was no time to continue the development. However I found the basic test script on other machine and added it.

**Comment by bojanpotocnik** [comment]
I just made another branch where pylink is used to directly connect to the J-Link, however right now when I started testing it I discovered the performance limit of that implementation :(
